// Mock dataset of scraped listings. Some fields deliberately null
// to exercise the placeholder behaviour.
const LISTINGS = [
  {
    id: "AMS-04821",
    address: "Apollolaan 154",
    postcode: "1077 BG",
    city: "Amsterdam",
    municipality: "Amsterdam",
    district: "Zuid / Apollobuurt",
    price: 1450000,
    priceType: "k.k.",
    pricePerM2: 9667,
    livingArea: 150,
    plotArea: null,
    bedrooms: 4,
    rooms: 6,
    energyLabel: "B",
    yearBuilt: 1928,
    type: "Bovenwoning",
    stilleVerkoop: true,
    nieuwbouw: false,
    agency: "Brecheisen Makelaars",
    agencyUrl: "brecheisen.nl",
    sourceUrl: "intern://feed/brecheisen/4821",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-18T07:30:00Z",
    description: "Karakteristieke bovenwoning in beschermd stadsgezicht, gelegen aan een van de meest gewilde lanen van Amsterdam Zuid. Drie woonlagen met originele en-suite kamers, schouwen en glas-in-loodramen. Recent gemoderniseerde keuken en twee badkamers. Zuid-georiënteerd dakterras met vrij uitzicht over de Apollobuurt. Aangeboden in stille verkoop via het netwerk van de makelaar; nog niet publiekelijk geadverteerd.",
    placeholder: { hue: 32, label: "AMS-04821" },
    floorPlans: 3,
    images: 14,
  },
  {
    id: "UTR-00917",
    address: "Cartesiusweg 145 — Bouwnr. 28",
    postcode: "3534 BA",
    city: "Utrecht",
    municipality: "Utrecht",
    district: "Cartesiusdriehoek",
    price: 495000,
    priceType: "v.o.n.",
    pricePerM2: 5824,
    livingArea: 85,
    plotArea: null,
    bedrooms: 2,
    rooms: 3,
    energyLabel: "A++",
    yearBuilt: 2026,
    type: "Appartement",
    stilleVerkoop: false,
    nieuwbouw: true,
    agency: "Boelens Jorritsma",
    agencyUrl: "boelensjorritsma.nl",
    sourceUrl: "https://nieuwbouw.example/cartesius/28",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-17T14:00:00Z",
    description: "Onderdeel van fase 3 van het Cartesius-project: een autoluwe stadswijk met ruim 700 woningen rond een centraal park. Het appartement op de 6e verdieping beschikt over een ruim balkon op het westen en uitzicht over het Merwedekanaal. Hoogwaardig afgewerkt door de aannemer; oplevering Q3 2027.",
    placeholder: { hue: 195, label: "UTR-00917" },
    floorPlans: 2,
    images: 8,
  },
  {
    id: "DHG-02233",
    address: "Frederik Hendriklaan 287",
    postcode: "2582 BX",
    city: "Den Haag",
    municipality: "Den Haag",
    district: "Statenkwartier",
    price: 1195000,
    priceType: "k.k.",
    pricePerM2: 7710,
    livingArea: 155,
    plotArea: 220,
    bedrooms: 4,
    rooms: 5,
    energyLabel: "C",
    yearBuilt: 1912,
    type: "Herenhuis",
    stilleVerkoop: true,
    nieuwbouw: false,
    agency: "Voorma & Beheer",
    agencyUrl: "voorma-beheer.nl",
    sourceUrl: "intern://feed/voorma/2233",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-17T19:12:00Z",
    description: "Statig herenhuis in het Statenkwartier, op loopafstand van het strand en de winkels van de Fred. Vier verdiepingen, originele ornamenten in plafonds en wanden, parketvloeren, en een diepe zonnige tuin op het zuidwesten met achterom. De woning wordt discreet aangeboden via een select netwerk.",
    placeholder: { hue: 18, label: "DHG-02233" },
    floorPlans: 4,
    images: 22,
  },
  {
    id: "HRL-00408",
    address: "Kleverlaan 62",
    postcode: "2023 JG",
    city: "Haarlem",
    municipality: "Haarlem",
    district: "Kleverpark",
    price: 875000,
    priceType: "k.k.",
    pricePerM2: 6964,
    livingArea: 126,
    plotArea: 180,
    bedrooms: 3,
    rooms: 4,
    energyLabel: "D",
    yearBuilt: 1924,
    type: "Tussenwoning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "Kuijs Reinder Kakes",
    agencyUrl: "krk.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/kleverlaan-62",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-17T11:00:00Z",
    description: "Jaren-'20 tussenwoning in Kleverpark met originele details: paneeldeuren, glas-in-lood en een granieten gang. Drie volwaardige slaapkamers, vaste trap naar de zolderkamer. Diepe tuin op het zuiden van bijna 14 meter, voorzien van een gemetselde berging.",
    placeholder: { hue: 88, label: "HRL-00408" },
    floorPlans: 2,
    images: 18,
  },
  {
    id: "RTM-01156",
    address: "Wilhelminakade 308 — Toren B",
    postcode: "3072 AP",
    city: "Rotterdam",
    municipality: "Rotterdam",
    district: "Kop van Zuid",
    price: 729000,
    priceType: "v.o.n.",
    pricePerM2: 7434,
    livingArea: 98,
    plotArea: null,
    bedrooms: 2,
    rooms: 3,
    energyLabel: "A+",
    yearBuilt: 2025,
    type: "Appartement",
    stilleVerkoop: false,
    nieuwbouw: true,
    agency: "Ooms Makelaars",
    agencyUrl: "ooms.com",
    sourceUrl: "https://nieuwbouw.example/wilhelminakade/b-1804",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-16T09:00:00Z",
    description: "18e verdieping in de net opgeleverde Toren B, met panoramisch uitzicht over de Maas, de Erasmusbrug en de skyline van Rotterdam. Floor-to-ceiling beglazing, twee balkons. Eigen parkeerplaats in de gebouwde parkeergarage (optioneel, € 65.000 v.o.n.).",
    placeholder: { hue: 215, label: "RTM-01156" },
    floorPlans: 1,
    images: 11,
  },
  {
    id: "DLF-00674",
    address: "Vermeerstraat 14",
    postcode: "2613 RH",
    city: "Delft",
    municipality: "Delft",
    district: "Olofsbuurt",
    price: 545000,
    priceType: "k.k.",
    pricePerM2: null,
    livingArea: null,
    plotArea: 96,
    bedrooms: 3,
    rooms: null,
    energyLabel: null,
    yearBuilt: 1931,
    type: "Tussenwoning",
    stilleVerkoop: true,
    nieuwbouw: false,
    agency: "Van der Goes & De Vries",
    agencyUrl: "vdgdv.nl",
    sourceUrl: "intern://feed/vdgdv/0674",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-16T16:48:00Z",
    description: "Karakteristieke jaren-'30 woning in de gewilde Olofsbuurt, op fietsafstand van de binnenstad en het station. De makelaar deelt foto's en plattegronden alleen op aanvraag; bezichtigingen lopen via een ingeschreven kring van geïnteresseerden.",
    placeholder: { hue: 158, label: "DLF-00674" },
    floorPlans: 0,
    images: 4,
  },
  {
    id: "LDN-01029",
    address: "Burggravenlaan 41",
    postcode: "2313 HS",
    city: "Leiden",
    municipality: "Leiden",
    district: "Professorenwijk",
    price: 695000,
    priceType: "k.k.",
    pricePerM2: 5806,
    livingArea: 120,
    plotArea: 145,
    bedrooms: 4,
    rooms: 5,
    energyLabel: "C",
    yearBuilt: 1929,
    type: "Hoekwoning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "De Leeuw Makelaars",
    agencyUrl: "deleeuw.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/burggravenlaan-41",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-15T13:25:00Z",
    description: "Royale hoekwoning in de Professorenwijk met een vrijstaande stenen berging in de achtertuin. Onlangs aan de buitenzijde geschilderd, dak vernieuwd in 2021. De plattegrond is praktisch met een lichte L-vormige woonkamer en een aparte werkkamer op de begane grond.",
    placeholder: { hue: 45, label: "LDN-01029" },
    floorPlans: 3,
    images: 19,
  },
  {
    id: "AMS-04795",
    address: "Linnaeusparkweg 88-2",
    postcode: "1098 EJ",
    city: "Amsterdam",
    municipality: "Amsterdam",
    district: "Watergraafsmeer",
    price: 625000,
    priceType: "k.k.",
    pricePerM2: 8784,
    livingArea: 71,
    plotArea: null,
    bedrooms: 2,
    rooms: 3,
    energyLabel: "C",
    yearBuilt: 1931,
    type: "Bovenwoning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "Hoekstra en van Eck",
    agencyUrl: "hoekstraenvaneck.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/linnaeusparkweg-88-2",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-15T10:11:00Z",
    description: "Lichte bovenwoning op de tweede en derde etage, met een dakterras op het zuidwesten. Vlakbij het Park Frankendael en het Oosterpark. De woning beschikt over een eigen entree en is volledig gerenoveerd in 2019.",
    placeholder: { hue: 130, label: "AMS-04795" },
    floorPlans: 2,
    images: 16,
  },
  {
    id: "GRN-00302",
    address: "Hereweg 78",
    postcode: "9725 AG",
    city: "Groningen",
    municipality: "Groningen",
    district: "Herewegbuurt",
    price: 425000,
    priceType: "k.k.",
    pricePerM2: 4250,
    livingArea: 100,
    plotArea: 130,
    bedrooms: 3,
    rooms: 4,
    energyLabel: "E",
    yearBuilt: 1905,
    type: "Benedenwoning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "Rotsvast Groningen",
    agencyUrl: "rotsvast.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/hereweg-78",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-14T15:45:00Z",
    description: "Karakteristieke benedenwoning met diepe achtertuin in de Herewegbuurt. Originele en-suite kamers en hoge plafonds; vraagt op enkele plekken cosmetisch onderhoud. Op loopafstand van het Sterrebos en het Hoofdstation.",
    placeholder: { hue: 285, label: "GRN-00302" },
    floorPlans: 1,
    images: 9,
  },
  {
    id: "EHV-00518",
    address: "Strijp-S — Sectie 12, Bouwnr. 144",
    postcode: "5617 AA",
    city: "Eindhoven",
    municipality: "Eindhoven",
    district: "Strijp-S",
    price: 389500,
    priceType: "v.o.n.",
    pricePerM2: null,
    livingArea: null,
    plotArea: null,
    bedrooms: null,
    rooms: null,
    energyLabel: "A++",
    yearBuilt: 2027,
    type: "Appartement",
    stilleVerkoop: false,
    nieuwbouw: true,
    agency: "Bouwinvest Residential",
    agencyUrl: "bouwinvest.nl",
    sourceUrl: "https://nieuwbouw.example/strijp-s/144",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-14T08:00:00Z",
    description: "Voorinschrijving geopend voor fase 2 van Strijp-S, een herontwikkeling van het voormalige Philips-terrein. Specificaties per bouwnummer worden vrijgegeven na inschrijving; verwachte oplevering Q1 2027. Sectie 12 ligt direct aan het Ketelhuisplein.",
    placeholder: { hue: 250, label: "EHV-00518" },
    floorPlans: 0,
    images: 3,
  },
  {
    id: "AMS-04760",
    address: "Prinsengracht 412",
    postcode: "1016 JC",
    city: "Amsterdam",
    municipality: "Amsterdam",
    district: "Grachtengordel-West",
    price: 2350000,
    priceType: "k.k.",
    pricePerM2: 13294,
    livingArea: 177,
    plotArea: null,
    bedrooms: 3,
    rooms: 5,
    energyLabel: "F",
    yearBuilt: 1672,
    type: "Grachtenpand",
    stilleVerkoop: true,
    nieuwbouw: false,
    agency: "Sotheby's International Realty NL",
    agencyUrl: "sothebysrealty.nl",
    sourceUrl: "intern://feed/sothebys/4760",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-13T20:22:00Z",
    description: "Beletage-appartement in een 17e-eeuws grachtenpand aan de Prinsengracht, op steenworp afstand van de Negen Straatjes. Authentieke bedstedes, geschilderde plafonds toegeschreven aan de school van Jacob de Wit, en een witte marmeren gang. Wordt discreet aangeboden binnen het off-market netwerk van de makelaar.",
    placeholder: { hue: 5, label: "AMS-04760" },
    floorPlans: 2,
    images: 24,
  },
  {
    id: "ZWL-00088",
    address: "Veerallee 21",
    postcode: "8019 AB",
    city: "Zwolle",
    municipality: "Zwolle",
    district: "Veerallee",
    price: 1050000,
    priceType: "k.k.",
    pricePerM2: 4795,
    livingArea: 219,
    plotArea: 412,
    bedrooms: 5,
    rooms: 7,
    energyLabel: "B",
    yearBuilt: 1908,
    type: "Vrijstaande woning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "Ridder & De Vries",
    agencyUrl: "ridderdevries.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/veerallee-21",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-13T11:30:00Z",
    description: "Riante vrijstaande villa aan de monumentale Veerallee, ontworpen in 1908 door de Zwolse architect G.G. Post. Vijf slaapkamers, een orangerie aan de tuinzijde en een vrijstaand koetshuis dat dienst doet als atelier. De tuin is ontworpen door Mien Ruys en wordt onderhouden door een tuinarchitect.",
    placeholder: { hue: 105, label: "ZWL-00088" },
    floorPlans: 3,
    images: 27,
  },
  {
    id: "GMR-00041",
    address: "Brediusweg 14",
    postcode: "1401 AG",
    city: "Bussum",
    municipality: "Gooise Meren",
    district: "Spiegel",
    price: 1295000,
    priceType: "k.k.",
    pricePerM2: 6809,
    livingArea: 190,
    plotArea: 480,
    bedrooms: 5,
    rooms: 7,
    energyLabel: "C",
    yearBuilt: 1922,
    type: "Vrijstaande woning",
    stilleVerkoop: true,
    nieuwbouw: false,
    agency: "Eefje Voogd Makelaardij",
    agencyUrl: "eefjevoogd.nl",
    sourceUrl: "intern://feed/voogd/0041",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-16T10:22:00Z",
    description: "Vrijstaande villa in het Spiegelkwartier, op loopafstand van het centrum van Bussum en NS-station Naarden-Bussum. Vijf slaapkamers, een lichte serre, en een diepe achtertuin met monumentale beuk. Aangeboden in stille verkoop binnen de regio.",
    placeholder: { hue: 65, label: "GMR-00041" },
    floorPlans: 3,
    images: 17,
  },
  {
    id: "GMR-00042",
    address: "Cattenhagestraat 9",
    postcode: "1411 CR",
    city: "Naarden",
    municipality: "Gooise Meren",
    district: "Vesting",
    price: 825000,
    priceType: "k.k.",
    pricePerM2: 6346,
    livingArea: 130,
    plotArea: 95,
    bedrooms: 3,
    rooms: 4,
    energyLabel: "D",
    yearBuilt: 1898,
    type: "Tussenwoning",
    stilleVerkoop: false,
    nieuwbouw: false,
    agency: "Eefje Voogd Makelaardij",
    agencyUrl: "eefjevoogd.nl",
    sourceUrl: "https://www.example-funda-mirror.nl/cattenhagestraat-9",
    scrapedAt: "2026-05-18T08:42:11Z",
    listedAt: "2026-05-15T08:30:00Z",
    description: "Karakteristiek pand binnen de vesting van Naarden, voorheen in gebruik als ateliers. Volledig gerenoveerd in 2018, met behoud van de balkenplafonds en originele schouw. Op fietsafstand van het IJmeer en Spant!",
    placeholder: { hue: 175, label: "GMR-00042" },
    floorPlans: 2,
    images: 13,
  },
];

window.LISTINGS = LISTINGS;
